apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list